services:
  - type: web
    name: Gym-Member-Management-Backend
    runtime: java
    env: java
    region: frankfurt
    plan: free
    buildCommand: cd Server/GymCustomers && mvn clean package -DskipTests
    startCommand: cd Server/GymCustomers && java -Dserver.port=$PORT -jar target/GymCustomers-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: "17"
      - key: SPRING_PROFILES_ACTIVE
        value: prod
